create schema if not exists clean;

drop table if exists clean.feature_eng;

create table clean.feature_eng (
	"inspection_id"  integer,
	"dba_name" text,
	# "aka_name" text,
	"license_num"  integer,
	"facility_type" text,
	"risk"  integer,
	"address" text,
	"zip" text,
	"inspection_date" "date",
	"inspection_type" text,
	"results" text,
	"violations" text,
	"latitude" "double precision",
	"longitude" "double precision",
	"inspection_year"  integer,
	"pass" text,
	"days_since_last_inspection"  integer,
	"approved_insp"  integer,
	"num_viol_last_insp"  integer,
	"mon" text,
	"tue" text,
	"wed" text,
	"thu" text,
	"fri" text,
	"sat" text,
	"sun" text,
	"ene" text,
	"feb" text,
	"mar" text,
	"abr" text,
	"may" text,
	"jun" text,
	"jul" text,
	"ago" text,
	"sep" text,
	"oct" text,
	"nov" text,
	"dic" text,
	"inspection_month"  integer
 );
